version: '3.7'

services:

  webapp:
    container_name: disp51
    build:
      context: .
      dockerfile: Dockerfile
    image: disp:0.0.51
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true